### ISSUE TITLE
Faust crashes on Mac OS X Catalina 10.15.7 if use consumer with asyncio.get_event_loop

### ISSUE THREAD

**Issue by ice1x** [faust-streaming/faust#164]
## Checklist

- [ ] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
1. Create simple consumer and producer using Faust manual (https://faust.readthedocs.io/en/latest/userguide/agents.html)
2. Run, make sure it works well
3. Add CPU-bound function to consumer (from here https://docs.python.org/3/library/asyncio-eventloop.html)

## Expected behavior
Works fine like on Ubunto 20

## Actual behavior
Crashes on osx

## Full traceback

```
[2021-06-29 01:07:41,363] [89239] [INFO] [^Worker]: Stopping... 
[2021-06-29 01:07:41,364] [89239] [INFO] [^-App]: Stopping... 
[2021-06-29 01:07:41,364] [89239] [INFO] [^-App]: Flush producer buffer... 
[2021-06-29 01:07:41,365] [89239] [INFO] [^--TableManager]: Stopping... 
[2021-06-29 01:07:41,365] [89239] [INFO] [^---Fetcher]: Stopping... 
[2021-06-29 01:07:41,366] [89239] [INFO] [^---Conductor]: Stopping... 
[2021-06-29 01:07:41,367] [89239] [INFO] [^--AgentManager]: Stopping... 
[2021-06-29 01:07:41,367] [89239] [INFO] [^Agent: __mp_main__.adding]: Stopping... 
[2021-06-29 01:07:41,369] [89239] [INFO] [^--ReplyConsumer]: Stopping... 
[2021-06-29 01:07:41,370] [89239] [INFO] [^--LeaderAssignor]: Stopping... 
[2021-06-29 01:07:41,371] [89239] [INFO] [^--Consumer]: Stopping... 
[2021-06-29 01:07:41,374] [89239] [INFO] [^--Web]: Stopping... 
[2021-06-29 01:07:41,375] [89239] [INFO] [^---Server]: Stopping... 
[2021-06-29 01:07:41,375] [89239] [INFO] [^--Web]: Cleanup 
[2021-06-29 01:07:41,377] [89239] [INFO] [^--CacheBackend]: Stopping... 
[2021-06-29 01:07:41,377] [89239] [INFO] [^--Producer]: Stopping... 
[2021-06-29 01:07:41,380] [89239] [INFO] [^---ProducerBuffer]: Stopping... 
[2021-06-29 01:07:41,385] [89239] [INFO] [^--Monitor]: Stopping... 
[2021-06-29 01:07:41,388] [89239] [INFO] [^Worker]: Gathering service tasks... 
[2021-06-29 01:07:41,389] [89239] [INFO] [^Worker]: Gathering all futures... 
[2021-06-29 01:07:42,395] [89239] [INFO] [^Worker]: Closing event loop 
[2021-06-29 01:07:42,454] [89233] [ERROR] [^----Agent*: __main__.adding]: Crashed reason=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.') 
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/kaf_send/lib/python3.9/site-packages/faust/agents/agent.py", line 647, in _execute_actor
    await coro
  File "/usr/local/anaconda3/envs/kaf_send/lib/python3.9/site-packages/faust/agents/agent.py", line 664, in _slurp
    async for value in it:
  File "/Users/cold00n/repo/kaf_send/main.py", line 29, in adding
    result = await loop.run_in_executor(pool, cpu_bound)
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[2021-06-29 01:07:42,456] [89233] [INFO] [^----OneForOneSupervisor: (1@0x7fd6b6d18f70)]: Restarting dead <Agent*: __main__.adding>! Last crash reason: BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.') 
NoneType: None
```

# Versions

* Python version 3.8/3.9
* Faust version 1.10.4
* Operating system Mac OS X Catalina 10.15.7
* Kafka version aiokafka=1.1.6 
*% kafka-server-start --version
[2021-06-29 01:06:34,887] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
2.8.0 (Commit:ebb1d6e21cc92130)
* RocksDB version (if applicable)

**Comment by ice1x** [comment]
`import faust
import asyncio
import concurrent.futures

app = faust.App('myapp', broker='kafka://127.0.0.1:9092')


class Add(faust.Record):
    a: int
    b: int


topic = app.topic('test', value_type=Add)
out = app.topic('out', value_type=int)


def cpu_bound():
    # CPU-bound operations will block the event loop:
    # in general it is preferable to run them in a
    # process pool.
    return sum(i * i for i in range(10 ** 7))


@app.agent(topic, sink=[out])
async def adding(stream):
    async for value in stream:
        loop = asyncio.get_event_loop()
        with concurrent.futures.ProcessPoolExecutor() as pool:
            result = await loop.run_in_executor(pool, cpu_bound)
            print('custom process pool', result)

        yield value.a + value.b

app.main()
`

**Comment by ice1x** [comment]
```
"""Simple Faust Producer"""
import faust


class Add(faust.Record):
    a: int
    b: int


msg = Add(a=1, b=2)


if __name__ == '__main__':
    """Simple Faust Producer"""

    app = faust.App('faust_test_app', broker='kafka://127.0.0.1:9092')
    topic = app.topic('test')

    @app.timer(interval=1.0)
    async def send_message(message):
        await topic.send(value=msg)
    app.main()
```
