### ISSUE TITLE
SetTable crashes when using RocksDB

### ISSUE THREAD

**Issue by elja** [faust-streaming/faust#261]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

If you use "rocksdb" as storage you got this error, it doesn't happen if you use memory. 

Basically, I have a list of tasks that I load from the database and store locally (no kafka here), then I have some external events that are triggering execution of these tasks, the only thing I want is to not send a task to a kafka if it's already was sent and currently processing. I use a SetTable to track the progress of the task execution. All topics and this table have the same number of partitions and also use the same key, so they should be co-partitioned. 

```python
app = faust.App(
    id=f"scheduler_{config.ENV}",
    broker=config.KAFKA_BOOTSTRAP_SERVERS,
    store='rocksdb://'
)

events_topic = app.topic('external_events', partitions=8) # events from another service, pertiotioned by some event_key

task_queue_topic = app.topic('task_queue_topic', partitions=8)
task_completion_topic = app.topic('task_completion_topic', partitions=8)
task_progress = app.SetTable('task_progress', partitions=8, value_type=int)

async def task_queue_sink(task):
    logging.info(f"Sending task: task_id = {task.task_id} / uuid = {task.uuid}")
    await task_queue_topic.send(key=task.event_key, value=task)

@app.agent(events_topic, sink=[task_queue_sink])
async def events_stream(stream: faust.Stream):
    async for key, event in stream.items():
        tasks = await maybe_load_tasks_from_db(event_key=key) # or event.event_key

        for task in tasks:
            if task.task_id not in task_progress[event_key]:
                task_progress[event_key].add(task.task_id)
                yield task

@app.agent(task_completion_topic)
async def task_completion_stream(stream: faust.Stream):
    async for task in stream:
        logging.info(f"Task completed: task_id = {task.task_id} / uuid = {task.uuid}")
        task_progress[task.event_key].discard(task.task_id)
```

Tell us what you did to cause something to happen.

## Expected behavior

I should be able to store data to the SetTable that uses RocksDB without any errors.

## Actual behavior

`AssertionError: assert event is not None`
../python3.9/site-packages/faust/stores/rocksdb.py#274

## Full traceback

```pytb



[2022-01-19 14:26:10,389] [33567] [ERROR] [^----ChangeloggedSetManager: None]: Crashed reason=AssertionError() 
Traceback (most recent call last):
  File "******/projects/scheduler/.venv/lib/python3.9/site-packages/mode/services.py", line 802, in _execute_task
    await task
  File "******/projects/scheduler/.venv/lib/python3.9/site-packages/faust/tables/objects.py", line 146, in _periodic_flush
    self.flush_to_storage()
  File "******/projects/scheduler/.venv/lib/python3.9/site-packages/faust/tables/objects.py", line 139, in flush_to_storage
    self.storage[key] = self.data[key].as_stored_value()
  File "******/projects/scheduler/.venv/lib/python3.9/site-packages/faust/stores/base.py", line 208, in __setitem__
    return self._set(self._encode_key(key), self._encode_value(value))
  File "******/projects/scheduler/.venv/lib/python3.9/site-packages/faust/stores/rocksdb.py", line 274, in _set
    assert event is not None
AssertionError
[2022-01-19 14:26:10,398] [33567] [INFO] [^Worker]: Stopping... 
[2022-01-19 14:26:10,399] [33567] [INFO] [^-App]: Stopping... 
```

# Versions

* Python version = 3.9.5
* Faust version = 0.8.0
* Operating system = macOS Monterey M1 (Apple Silicone)
* Kafka version = 3.0.0
* RocksDB version (if applicable) = must be latest (6.27.3)

**Comment by j123b567** [comment]
Can be reproduced also by example `examples/tableofset.py` jsut by adding `store='rocksdb://'`

**Comment by j123b567** [comment]
Code that produces assert is similar to all other table operations where there is this code instead
```python
        if event is None:
            raise RuntimeError("Operation outside of stream iteration")
```

After examining the code, this is exactly the case. The table is written outside of the stream iteration. There is a separate periodic task that takes the memory representation and tries to flush it out to the RocksDB table. However, this cannot work. I just don't understand how it can work at all any time, because it is broken by design.

**Comment by elja** [comment]
@j123b567 I highly recommend you to use java spring + kafka streams directly if it's possible. After spending multiple days on faust I decided to switch and after a couple of days of learning, I did what I wanted. I thought that fixing issues that you face with faust will require you to contribute to this repo A LOT. Faust is a great tool and this is really sad that nobody maintains it, and on the other hand, only people who know kafka steams well can do it.

**Comment by j123b567** [comment]
@elja my app is now functional and using faust-streaming :D but this proposal will be probably my next step.

**Comment by wbarnha** [comment]
I took a look at your example and this part caught my attention:
```python3
async def task_queue_sink(job):
    logging.info(f"Sending task: task_id = {job['task_id']} / uuid = {job['uuid']}")
    await task_queue_topic.send(key=job['key'], value=job)
    tasks_progress[job['key']].add(job['task_id'])
```

Using this as an agent sink to modify a table is entering murky waters. Taken from https://faust.readthedocs.io/en/latest/userguide/agents.html#concurrency:

>Warning:
>
>Concurrent instances of an agent will process the stream out-of-order, so you cannot mutate [tables](https://faust.readthedocs.io/en/latest/userguide/tables.html#guide-tables) from within the agent function:
>
>An agent having concurrency > 1, can only read from a table, never write.

I haven't tried writing to a Table using your methodology, so i'm afraid I can't be too helpful. 

`memory` storage works because it's a `base.Store` and is pretty stable. The `rocksdb` driver is derived from the `base.SerializedStore` class. The functionality required for the `rocksdb` driver to satisfy your use-case will require some changes made to faust.
