### ISSUE TITLE
murmur2 import error when using rocksDB

### ISSUE THREAD

**Issue by fonty422** [faust-streaming/faust#311]
## Steps to reproduce
Developing using `memory://` and am looking to move to production and use `rocksdb://`

## Expected behavior
Successfully import necessary packages and methods

## Actual behavior
Fails to import murmur2 (see blow)
I can confirm that I can see murmur2 in the kafka/partitioner/jhashed.py file

## Full traceback

```pytb
C:\Users\debooyj\Documents\scramble>faust -A kafka_services.update_web_client_stream:app --datadir=./kafka_services/kafka-logs/update_web_client_stream_0 worker -l info -p 6071
Traceback (most recent call last):
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\debooyj\AppData\Local\Programs\Python\Python38-32\Scripts\faust.exe\__main__.py", line 7, in <module>
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\cli\base.py", line 423, in make_context
    self._maybe_import_app()
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\cli\base.py", line 388, in _maybe_import_app
    find_app(appstr)
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\cli\base.py", line 312, in find_app
    val = symbol_by_name(app, imp=imp)
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\mode\utils\imports.py", line 262, in symbol_by_name
    module = imp(  # type: ignore
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\mode\utils\imports.py", line 376, in import_from_cwd
    return imp(module, package=package)
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\debooyj\Documents\scramble\kafka_services\update_web_client_stream.py", line 38, in <module>
    class App(faust.App):
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\__init__.py", line 261, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\app\__init__.py", line 2, in <module>
    from .base import App, BootStrategy
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\app\base.py", line 55, in <module>
    from faust import transport
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\transport\__init__.py", line 2, in <module>
    from .drivers import by_name, by_url
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\transport\drivers\__init__.py", line 4, in <module>
    from .aiokafka import Transport as AIOKafkaTransport
  File "c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\faust\transport\drivers\aiokafka.py", line 44, in <module>
    from kafka.partitioner import murmur2
ImportError: cannot import name 'murmur2' from 'kafka.partitioner' (c:\users\debooyj\appdata\local\programs\python\python38-32\lib\site-packages\kafka\partitioner\__init__.py)
```

# Versions

* Python version = 3.7
* Faust version = 0.8.4
* Operating system = Windows 10
* Kafka version = 13.2.8
* RocksDB version= 6.14.6

**Comment by fonty422** [comment]
Note, I did just update the faust package in order to get access to the `take_with_timestamp` method. I think I must have broken something by doing so.

**Comment by fonty422** [comment]
Never mind - I uninstalled and reinstalled and it worked fine. Still can't access rocksdb, though, despite it being installed.
