### ISSUE TITLE
faust.exceptions.ConsumerNotStarted: Consumer thread not yet started

### ISSUE THREAD

**Issue by mohammad-aqajani** [faust-streaming/faust#446]
## Steps to reproduce

everything is okay with the normal event loop

## Actual behavior

I was trying to use eventlet loop using `-L eventlet` arg.

## Full traceback

```pytb
Traceback (most recent call last):
  File "lib/python3.8/site-packages/mode/services.py", line 843, in _execute_task
    await task
  File "lib/python3.8/site-packages/faust/transport/consumer.py", line 902, in _commit_livelock_detector
    await self.verify_all_partitions_active()
  File "lib/python3.8/site-packages/faust/transport/consumer.py", line 906, in verify_all_partitions_active
    for tp in self.assignment():
  File "/lib/python3.8/site-packages/faust/transport/consumer.py", line 1441, in assignment
    return self._thread.assignment()
  File "lib/python3.8/site-packages/faust/transport/drivers/aiokafka.py", line 943, in assignment
    return ensure_TPset(self._ensure_consumer().assignment())
  File "/lib/python3.8/site-packages/faust/transport/drivers/aiokafka.py", line 977, in _ensure_consumer
    raise ConsumerNotStarted("Consumer thread not yet started")
faust.exceptions.ConsumerNotStarted: Consumer thread not yet started
```

# Versions

* Python version 3.8.13
* Faust version 0.10.4
* Operating system macos 13
* Kafka topics version 3.3.1

**Comment by hoanghonn** [comment]
Experiencing similar issue here. Any information regarding this bug?
