### ISSUE TITLE
Sensors crash when using `orjson` instead of `json`

### ISSUE THREAD

**Issue by elrik75** [faust-streaming/faust#451]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

When using `orjson` instead of built-in `json`, the encoding behavior is different about dict keys.
I think the `orjson` backend is less tested because when using sensors, the call crashes:

config:
```python
app.web.blueprints.add("/stats/", "faust.web.apps.stats:blueprint")
```

When calling `/stats` with the browser:

```pytb
[2023-02-20 17:22:42,831] [64185] [ERROR] Error handling request 
Traceback (most recent call last):
  ...
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/utils/json.py", line 184, in dumps
    return json_dumps(
TypeError: Dict key must be str
```

## Actual behavior

```python
>>> import json
>>> json.dumps({200: 1})  # Faust sensor http code counter
'{"200": 1}'
>>>  import orjson
>>> orjson.dumps({200: 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Dict key must be str
```

## Easy Fix:
If we want (almost) the same behavior between both, there is an easy fix with `OPT_NON_STR_KEYS`: https://github.com/ijl/orjson#opt_non_str_keys

```python
>>>  import orjson
>>> orjson.dumps({200: 1}, option=orjson.OPT_NON_STR_KEYS)
b'{"200":1}'
```

## Full traceback

```pytb
[2023-02-20 17:22:42,831] [64185] [ERROR] Error handling request 
Traceback (most recent call last):
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 108, in impl
    return await handler(request)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/web/drivers/aiohttp.py", line 246, in _dispatch
    return await handler(request)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/web/views.py", line 102, in __call__
    return await self.dispatch(request)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/web/views.py", line 118, in dispatch
    response = await method(cast(Request, request), **kwargs)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/web/apps/stats.py", line 31, in get
    return self.json({f"Sensor{i}": s.asdict() for i, s in enumerate(self.app.sensors)})
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/web/views.py", line 248, in json
    return self.web.json(
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/web/drivers/aiohttp.py", line 181, in json
    payload: Any = _json.dumps(value)
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.10/site-packages/faust/utils/json.py", line 184, in dumps
    return json_dumps(
TypeError: Dict key must be str
```

# Versions

* Python version: CPython 3.10.8 (Linux x86_64) + uvloop
* Faust version:  0.10.3

**Comment by wbarnha** [comment]
Thanks for the bug report, and an easy fix! I'll get these changes merged in soon.
