### ISSUE TITLE
Bad status line 'Invalid method encountered'

### ISSUE THREAD

**Issue by bhanuka-ilume** [faust-streaming/faust#516]
Has anyone faced this issue? 

## Checklist

- [X] I have included information about relevant versions
- [X] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

The consumer works normally for a day or two and randomly i get this error in the log file and it crashes.

```
[2023-06-09 19:59:42,444] [1] [ERROR] Error handling request
Traceback (most recent call last):
	File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
		messages, upgraded, tail = self._request_parser.feed_data(data)
	File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

## Expected behavior

Error should not be thrown

## Actual behavior

It crashes and stops consuming

# Versions

* Python version: 3.10
* Faust version: 0.9.5
* Operating system: Linux
* Kafka version: 2.6.2
* RocksDB version (if applicable)

The consumer is hosted through AWS ECS and the kafka brokers are hosted on Amazon MSK.

**Comment by wbarnha** [comment]
Never seen this one before, could you show us an example of your code? To be honest I think it's an `aiohttp` bug more than a Faust one specifically.
