### ISSUE TITLE
Cannot connect to Kafka (MSK) using TLS or IAM based authentication

### ISSUE THREAD

**Issue by vjanz** [faust-streaming/faust#548]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Set up a Kafka cluster in AWS (MSK) with TLS enabled on port 9094.
Use the following code to configure Faust to connect to the Kafka cluster with TLS:

```
import base64
import os
import boto3
import faust
from django.conf import settings

os.environ.setdefault('FAUST_LOOP', 'eventlet')

# Set the default Django settings module for the 'faust' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'conf.settings.production')
KAFKA_CONSUMER_GROUP = "my-consumer-group"

app = faust.App(KAFKA_CONSUMER_GROUP, autodiscover=False, origin='applications')

def get_kafka_bootstrap_servers():
    if kafka_arn := settings.KAFKA_ARN:
        resource = boto3.client("kafka", region_name="eu-central-1")
        response = resource.get_bootstrap_brokers(ClusterArn=base64.b64decode(kafka_arn).decode("utf-8"))
        bootstrap_servers = response.get("BootstrapBrokerStringTls").split(",")
        return [f"kafka://{host}" for host in bootstrap_servers]

@app.on_configured.connect
def configure_from_settings(_app, conf, **kwargs):
    conf.broker = get_kafka_bootstrap_servers()

```
Attempt to connect to the Kafka cluster using Faust with TLS.

## Expected behavior

I expected Faust to successfully connect to the Kafka cluster using TLS on port 9094 and consume messages, just as it does when I switch the "BootstrapBrokerStringTls" with "BootstrapBrokerString" based on boto3 [Docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kafka/client/get_bootstrap_brokers.html#:~:text=%27BootstrapBrokerStringTls%27%3A%20%27string%27%2C)

## Actual behavior
I don't have the full traceback as I removed that MSK cluster because I couldn't connect to it.
FAMILADDR wrong or unexpected. 

## Full traceback
`HOST` represents my broker host which I did hide, but it's a AWS broker URL

```pytb
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id          | my_app                                                                                                                                                                    |
| transport   | [URL('kafka://<host>.kafka.eu-central-1.amazonaws.com:9094'), URL('kafka://<host>.kafka.eu-central-1.amazonaws.com:9094')]  |
| store       | memory:                                                                                                                                                                           |
| web         | http://localhost:6066/                                                                                                                                                            |
| log         | -stderr- (info)                                                                                                                                                                   |
| pid         | 7                                                                                                                                                                                 |
| hostname    | pod-faust-consumer-69d7755ccd-l4rkv                                                                                                                                            |
| platform    | CPython 3.9.6 (Linux x86_64)                                                                                                                                                      |
| drivers     |                                                                                                                                                                                   |
|   transport | aiokafka=1.1.6                                                                                                                                                                    |
|   web       | aiohttp=3.8.5                                                                                                                                                                     |
| datadir     | /usr/src/app/my_app-data                                                                                                                                                  |
| appdir      | /usr/src/app/my_app-data/v1                                                                                                                                               |
+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[2023-09-22 14:22:45,075] [7] [INFO] [^Worker]: Starting... 
[2023-09-22 14:22:45,079] [7] [INFO] [^-App]: Starting... 
[2023-09-22 14:22:45,080] [7] [INFO] [^--Monitor]: Starting... 
[2023-09-22 14:22:45,080] [7] [INFO] [^--Producer]: Starting... 
[2023-09-22 14:22:45,080] [7] [INFO] [^---ProducerBuffer]: Starting... 
[2023-09-22 14:24:55,615] [7] [ERROR] Unable connect to "<Host>.kafka.eu-central-1.amazonaws.com:9094": [Errno 110] Connect call failed ('10.0.59.238', 9094) 
[2023-09-22 14:27:06,683] [7] [ERROR] Unable connect to "<Host>.kafka.eu-central-1.amazonaws.com:9094": [Errno 110] Connect call failed ('10.0.95.126', 9094) 
[2023-09-22 14:27:06,684] [7] [ERROR] [^Worker]: Error: ConnectionError("Unable to bootstrap from [('b-2.stagingkafkacluster.6wo661.c3.kafka.eu-central-1.amazonaws.com', 9094, <AddressFamily.AF_UNSPEC: 0>), ('<Host>.kafka.eu-central-1.amazonaws.com', 9094, <AddressFamily.AF_UNSPEC: 0>)]") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.9/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.9/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
    await producer.start()
  File "/usr/local/lib/python3.9/site-packages/aiokafka/producer/producer.py", line 178, in start
    await self.client.bootstrap()
  File "/usr/local/lib/python3.9/site-packages/aiokafka/client.py", line 230, in bootstrap
    raise ConnectionError(
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('<Host>.kafka.eu-central-1.amazonaws.com', 9094, <AddressFamily.AF_UNSPEC: 0>), ('<Host>.kafka.eu-central-1.amazonaws.com', 9094, <AddressFamily.AF_UNSPEC: 0>)]
[2023-09-22 14:27:06,686] [7] [INFO] [^Worker]: Stopping... 
[2023-09-22 14:27:06,687] [7] [INFO] [^-App]: Stopping... 
[2023-09-22 14:27:06,687] [7] [INFO] [^-App]: Flush producer buffer... 
[2023-09-22 14:27:06,687] [7] [INFO] [^--TableManager]: Stopping... 
[2023-09-22 14:27:06,688] [7] [INFO] [^---Fetcher]: Stopping... 
[2023-09-22 14:27:06,688] [7] [INFO] [^---Conductor]: Stopping... 
[2023-09-22 14:27:06,688] [7] [INFO] [^--AgentManager]: Stopping... 
[2023-09-22 14:27:06,689] [7] [INFO] [^Agent: i[.]update_user_stream_processor]: Stopping... 
[2023-09-22 14:27:06,689] [7] [INFO] [^--ReplyConsumer]: Stopping... 
[2023-09-22 14:27:06,689] [7] [INFO] [^--LeaderAssignor]: Stopping... 
[2023-09-22 14:27:06,690] [7] [INFO] [^--Consumer]: Stopping... 
[2023-09-22 14:27:06,690] [7] [INFO] [^--Web]: Stopping... 
[2023-09-22 14:27:06,691] [7] [INFO] [^--CacheBackend]: Stopping... 
[2023-09-22 14:27:06,691] [7] [INFO] [^--Producer]: Stopping... 
[2023-09-22 14:27:06,691] [7] [INFO] [^---ProducerBuffer]: Stopping... 
[2023-09-22 14:27:06,692] [7] [INFO] [^--Monitor]: Stopping... 
[2023-09-22 14:27:06,693] [7] [INFO] [^Worker]: Gathering service tasks... 
[2023-09-22 14:27:06,693] [7] [INFO] [^Worker]: Gathering all futures... 
[2023-09-22 14:27:07,694] [7] [INFO] [^Worker]: Closing event loop 

```

# Versions

* Python version 
* Faust version **0.10.16**
* Operating system **Linux with python:3.9.6-slim Image, running on Kubernetes 1.25 and Kafka 2.8.1**
* Kafka version **2.8.1**

**Comment by vjanz** [comment]
I solved the issue by making these changes:

- Added broker_credentials when initializing the Faust App: 
```
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH)
```
- Add `security_protocol="SSL` when initializing the Faust App. So a complete configuration looks like this:

```
app = faust.App(
    KAFKA_CONSUMER_GROUP,
    autodiscover=False,
    origin="applications",
    security_protocol="SSL",
    broker_credentials=ssl_context,
)
```

It seems when you're trying to connect to Kafka MSK the `security_protocol` is really necessary, as before I tried only using broker_credentials and it didn't work. Adding the `security_protocl="SSL"` fixed the issue.
